### ISSUE TITLE
css: trailing `;` required with `@import`

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/file-deps#14]
this always gets me...

**index.css**

``` css
@import './something'
```

**something.css**

``` css
.Something {
  color: blue;
}
```

**build.css**

```
```

---

imo, omitting a `;` shouldn't break everything :/

/cc @matthewmueller @dominicbarnes
