### ISSUE TITLE
A duplicate edge-case

### ISSUE THREAD

**Issue by jasonkuhrt** [duojs/file-deps#7]
I thought of this while working on the PR to prune dupes: https://github.com/MatthewMueller/file-deps/pull/6

Currently these are considered different:

``` css
.a { background-image: url('z.png'); }
.b { background-image: url("./z.png"); }
```

It seems to me they should not be. Agreed?
